apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: tenants
spec:
  generators:
    - git:
        repoURL: https://github.com/syed-zizou/auto-sre.git
        revision: main
        files:
          - path: "tenant-discovery/**/config.yml"
  template:
    metadata:
      name: '{{tenant.id}}'
    spec:
      project: '{{appset_params.project}}'
      source:
        repoURL: '{{ appset_params.repoURL }}'
        targetRevision: HEAD
        path: 'apps/{{tenant.id}}'
        # path: 'apps/{{tenant.id}}/*/dev'
        # helm:
        #   valueFiles:
        #     - values.{{tenant.id}}.yaml
      destination:
        server: '{{k8s_cluster.address}}'
        namespace: '{{appset_params.namespace}}'
      syncPolicy:
        automated: {}