apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  type: host-namespace
  tenant: mt-dev-1F20D
helmGlobals:
  chartHome: ../../../../charts
helmCharts:
- name: namespace
  releaseName: namespace
  valuesFile: mt-dev-values.yaml
