apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  type: vcluster
  tenant: audi
  env: dev
helmGlobals:
  chartHome: ../../../../charts
helmCharts:
- name: vcluster
  releaseName: vcluster-audi
  valuesFile: values.yaml
  namespace: audi

