apiVersion: v1
kind: Secret
metadata:
  name: vc-{{ .Release.Name }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    app: vcluster
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
stringData:
  {{- if .Values.config }}
  config.yaml: {{ toJson .Values.config }}
  {{- else }}
  config.yaml: |-
    apiVersion: k0s.k0sproject.io/v1beta1
    kind: Cluster
    metadata:
      name: k0s
    spec:
      api:
        port: 6443
        k0sApiPort: 9443
        extraArgs:
          enable-admission-plugins: NodeRestriction
          endpoint-reconciler-type: none
      network:
        # Will be replaced automatically from the vcluster cli
        serviceCIDR: {{ .Values.serviceCIDR }}
        provider: custom
      controllerManager:
        extraArgs:
          {{- if not .Values.sync.nodes.enableScheduler }}
          controllers: '*,-nodeipam,-nodelifecycle,-persistentvolume-binder,-attachdetach,-persistentvolume-expander,-cloud-node-lifecycle'
          {{- else }}
          controllers: '*,-nodeipam,-persistentvolume-binder,-attachdetach,-persistentvolume-expander,-cloud-node-lifecycle'
          node-monitor-grace-period: 1h
          node-monitor-period: 1h
          {{- end }}
  {{- end }}